### ISSUE TITLE
Home Assistant integration polling interval

### ISSUE THREAD

**Issue by lwheeler** [bieniu/accuweather#396]
Maybe I am using this with HA incorrectly but I will state my issue. While using this integration with Home Assistant, the daily forecast only seems to update maybe 2 times a day. If I reload the integration then the forecast updates immediately. In the morning around 7 AM MST the forecast still shows the previous day. Is there a way to have the integration update more often?

**Comment by bieniu** [comment]
This is not a Home Assistant repository and this is not a right place to ask such a question.
Daily forecast data is fetched every 6 hours.
