### ISSUE TITLE
ApI not working or accpecting the Api key

### ISSUE THREAD

**Issue by alpha520098** [bieniu/accuweather#397]
The intergation has stopped working, So deleted the intergation and reinstalled with the correct API key and it doesnt accpect it suggesting that a error has occured:

so I've filled out the following questions and these are the answers below: 

Products*

**Core Weather Limited Trial**

MinuteCast
**MinuteCast Limited Trial**

Where will the API be used? * Desktop Website 

What will you be creating with this API? *
Internal App

Is this for Business to Business or Business to Consumer use? *
Business to Business

Is this Worldwide or Country specific use? *

Country ( Aus ) 

After obtaining the key cut and paste this into home assistant and it says a error has occured

**Comment by bieniu** [comment]
Read the documentation https://www.home-assistant.io/integrations/accuweather/
