### ISSUE TITLE
Additional Accuweather information

### ISSUE THREAD

**Issue by emeybee** [bieniu/accuweather#54]
Hi Maciej,

You seem to have created the Accuweather integration for Home Assistant so I'm hoping you can help me-- is there any way to access the other sensors in the API? For instance, in my area snow information is very important, but for some reason it wasn't included with the integration. The headline text would also be very useful. 

I know not everyone needs every sensor, but maybe they could be included but disabled so that we could enable them when needed.

I'm sure you have this already but just in case, here is the list of available data points that I found:
https://developer.accuweather.com/accuweather-forecast-api/apis/get/forecasts/v1/daily/5day/%7BlocationKey%7D

**Comment by bieniu** [comment]
If I understand correctly then you expect to add a new sensors to the integration. But this is not an integration repository. Feature requests for core integration should be opened here https://community.home-assistant.io/c/feature-requests/13

And please be more precise as I'm not sure what you need.
